Presentation
ZebraDevs/Zebra-Iota-Edge-SDK pull request #65
Opened 2021-12-23 13:37 UTC by 7opf

- Closes https://github.com/ZebraDevs/Zebra-Iota-Edge-SDK/issues/26
- Moves init call to main.ts (new changes causes cyclical import in holder app)

2021-12-23 13:40 UTC, 7opf commented
**Device ID**
![device id](https://user-images.githubusercontent.com/20902401/147248441-dee3e49c-4fe1-435c-8152-2d09bd2c819e.png)

**Holder**
![holder](https://user-images.githubusercontent.com/20902401/147248444-efa7b28c-08ff-4f8b-ab9c-c5a564b02f7d.png)

2021-12-23 19:42 UTC, jmcanterafonseca-iota requested changes
some comments

2021-12-23 19:42 UTC, jmcanterafonseca-iota commented on identity-enabler/deviceId-mobile-app/src/components/CredentialHeader.svelte
> +                >{credential.issuer.name}
be careful don't assume issuer.name is going to be always defined ...

2021-12-23 19:42 UTC, jmcanterafonseca-iota commented on identity-enabler/deviceId-mobile-app/src/components/CredentialHeader.svelte
> +            <span class="emphasis">{new Date(credential.issuanceDate).toLocaleString()}</span>
probably you need to be more explicit, specifying a locale, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString

2021-12-23 19:42 UTC, jmcanterafonseca-iota commented on identity-enabler/deviceId-mobile-app/rollup.config.js
> -
why is this change needed in this PR?

2021-12-23 19:42 UTC, jmcanterafonseca-iota commented on identity-enabler/deviceId-mobile-app/src/pages/Home.svelte
> +                        subheading="Issued by {vp.verifiableCredential.issuer.name}"
same comment

2021-12-23 19:42 UTC, jmcanterafonseca-iota commented on identity-enabler/holder-mobile-app/rollup.config.js
> -
same comment

2021-12-23 19:42 UTC, jmcanterafonseca-iota commented on identity-enabler/holder-mobile-app/src/components/CredentialHeader.svelte
> +                >{credential.issuer.name}
same comment

2021-12-23 19:42 UTC, jmcanterafonseca-iota commented on identity-enabler/holder-mobile-app/src/components/CredentialHeader.svelte
> +            <span class="emphasis">{new Date(credential.issuanceDate).toLocaleString()}</span>
set a locale explicitly as in other parts of the app

2021-12-23 19:42 UTC, jmcanterafonseca-iota commented on identity-enabler/holder-mobile-app/src/lib/helpers.ts
> -}
why is this function removed?

2021-12-23 19:42 UTC, jmcanterafonseca-iota commented on identity-enabler/holder-mobile-app/src/components/modal/Share.svelte
> +            console.error("Error sharing: " + error);
what happens if this happens?

2021-12-23 19:42 UTC, jmcanterafonseca-iota commented on identity-enabler/holder-mobile-app/src/pages/Credential.svelte
> -                <p>{new Date(preparedCredentialDocument.issuanceDate).toLocaleString()}</p>
same comment

2021-12-23 19:42 UTC, jmcanterafonseca-iota commented on identity-enabler/holder-mobile-app/src/pages/Home.svelte
> +                        subheading="Issued by {credential.issuer.name}"
same comment

2021-12-23 19:42 UTC, jmcanterafonseca-iota commented on identity-enabler/verifier-mobile-app/rollup.config.js
> -}
same comment

2021-12-23 19:42 UTC, jmcanterafonseca-iota commented on identity-enabler/verifier-mobile-app/src/components/CredentialHeader.svelte
> +                >{credential.issuer.name}
same comment

2021-12-23 19:42 UTC, jmcanterafonseca-iota commented on identity-enabler/verifier-mobile-app/src/components/CredentialHeader.svelte
> +            <span class="emphasis">{new Date(credential.issuanceDate).toLocaleString()}</span>
same comment

2021-12-23 19:42 UTC, jmcanterafonseca-iota commented on identity-enabler/verifier-mobile-app/src/pages/Home.svelte
> +                            subheading="Issued by {credential.issuer.name}"
same comment

2021-12-23 20:00 UTC, 7opf commented on identity-enabler/holder-mobile-app/src/lib/helpers.ts
> -}
It's no longer used after deletions.

2021-12-24 11:26 UTC, jmcanterafonseca-iota approved these changes
LGTM, thanks

2021-12-24 11:26 UTC, merged